// Representative minimized-bundle ambiguity fixture: 133 switch(<id>.type) sites,
// with one visibility-predicate-shaped candidate carrying the robust scoring signals.
function n001(A001){switch(A001.type){case"system":return false;default:return true}}
function n002(A002){switch(A002.type){case"system":return false;default:return true}}
function n003(A003){switch(A003.type){case"system":return false;default:return true}}
function n004(A004){switch(A004.type){case"system":return false;default:return true}}
function n005(A005){switch(A005.type){case"system":return false;default:return true}}
function n006(A006){switch(A006.type){case"system":return false;default:return true}}
function n007(A007){switch(A007.type){case"system":return false;default:return true}}
function n008(A008){switch(A008.type){case"system":return false;default:return true}}
function n009(A009){switch(A009.type){case"system":return false;default:return true}}
function n010(A010){switch(A010.type){case"system":return false;default:return true}}
function n011(A011){switch(A011.type){case"system":return false;default:return true}}
function n012(A012){switch(A012.type){case"system":return false;default:return true}}
function n013(A013){switch(A013.type){case"system":return false;default:return true}}
function n014(A014){switch(A014.type){case"system":return false;default:return true}}
function n015(A015){switch(A015.type){case"system":return false;default:return true}}
function n016(A016){switch(A016.type){case"system":return false;default:return true}}
function n017(A017){switch(A017.type){case"system":return false;default:return true}}
function n018(A018){switch(A018.type){case"system":return false;default:return true}}
function n019(A019){switch(A019.type){case"system":return false;default:return true}}
function n020(A020){switch(A020.type){case"system":return false;default:return true}}
function n021(A021){switch(A021.type){case"system":return false;default:return true}}
function n022(A022){switch(A022.type){case"system":return false;default:return true}}
function n023(A023){switch(A023.type){case"system":return false;default:return true}}
function n024(A024){switch(A024.type){case"system":return false;default:return true}}
function n025(A025){switch(A025.type){case"system":return false;default:return true}}
function n026(A026){switch(A026.type){case"system":return false;default:return true}}
function n027(A027){switch(A027.type){case"system":return false;default:return true}}
function n028(A028){switch(A028.type){case"system":return false;default:return true}}
function n029(A029){switch(A029.type){case"system":return false;default:return true}}
function n030(A030){switch(A030.type){case"system":return false;default:return true}}
function n031(A031){switch(A031.type){case"system":return false;default:return true}}
function n032(A032){switch(A032.type){case"system":return false;default:return true}}
function n033(A033){switch(A033.type){case"system":return false;default:return true}}
function n034(A034){switch(A034.type){case"system":return false;default:return true}}
function n035(A035){switch(A035.type){case"system":return false;default:return true}}
function n036(A036){switch(A036.type){case"system":return false;default:return true}}
function n037(A037){switch(A037.type){case"system":return false;default:return true}}
function n038(A038){switch(A038.type){case"system":return false;default:return true}}
function n039(A039){switch(A039.type){case"system":return false;default:return true}}
function n040(A040){switch(A040.type){case"system":return false;default:return true}}
function n041(A041){switch(A041.type){case"system":return false;default:return true}}
function n042(A042){switch(A042.type){case"system":return false;default:return true}}
function n043(A043){switch(A043.type){case"system":return false;default:return true}}
function n044(A044){switch(A044.type){case"system":return false;default:return true}}
function n045(A045){switch(A045.type){case"system":return false;default:return true}}
function n046(A046){switch(A046.type){case"system":return false;default:return true}}
function n047(A047){switch(A047.type){case"system":return false;default:return true}}
function n048(A048){switch(A048.type){case"system":return false;default:return true}}
function n049(A049){switch(A049.type){case"system":return false;default:return true}}
function n050(A050){switch(A050.type){case"system":return false;default:return true}}
function n051(A051){switch(A051.type){case"system":return false;default:return true}}
function n052(A052){switch(A052.type){case"system":return false;default:return true}}
function n053(A053){switch(A053.type){case"system":return false;default:return true}}
function n054(A054){switch(A054.type){case"system":return false;default:return true}}
function n055(A055){switch(A055.type){case"system":return false;default:return true}}
function n056(A056){switch(A056.type){case"system":return false;default:return true}}
function n057(A057){switch(A057.type){case"system":return false;default:return true}}
function n058(A058){switch(A058.type){case"system":return false;default:return true}}
function n059(A059){switch(A059.type){case"system":return false;default:return true}}
function n060(A060){switch(A060.type){case"system":return false;default:return true}}
function n061(A061){switch(A061.type){case"system":return false;default:return true}}
function n062(A062){switch(A062.type){case"system":return false;default:return true}}
function n063(A063){switch(A063.type){case"system":return false;default:return true}}
function n064(A064){switch(A064.type){case"system":return false;default:return true}}
function n065(A065){switch(A065.type){case"system":return false;default:return true}}
function n066(A066){switch(A066.type){case"system":return false;default:return true}}
function toolUseId(H){if(H.type==="attachment")return H.attachment.toolUseID;if(H.type==="assistant"){if(H.message.content[0]?.type!=="tool_use")return null;return H.message.content[0].id}if(H.type==="user"){if(H.message.content[0]?.type!=="tool_result")return null;return H.message.content[0].tool_use_id}if(H.type==="progress")return H.toolUseID;if(H.type==="system")return H.subtype==="informational"?H.toolUseID??null:null}
function visibilityPredicate(X,$,q,K,_,A){if(_==="transcript")return!0;switch(X.type){case"attachment":case"user":case"assistant":{if(X.type==="assistant"){let Y=X.message.content[0];if(Y?.type==="server_tool_use")return A.resolvedToolUseIDs.has(Y.id)}let z=toolUseId(X);if(!z)return!0;if($.has(z))return!1;if(q.has(z))return!1;return K.has(z)}case"system":return X.subtype!=="api_error";case"grouped_tool_use":return X.messages.every((Y)=>A.resolvedToolUseIDs.has(Y.message.content[0].id));case"collapsed_read_search":return!1}}
function n067(A067){switch(A067.type){case"system":return false;default:return true}}
function n068(A068){switch(A068.type){case"system":return false;default:return true}}
function n069(A069){switch(A069.type){case"system":return false;default:return true}}
function n070(A070){switch(A070.type){case"system":return false;default:return true}}
function n071(A071){switch(A071.type){case"system":return false;default:return true}}
function n072(A072){switch(A072.type){case"system":return false;default:return true}}
function n073(A073){switch(A073.type){case"system":return false;default:return true}}
function n074(A074){switch(A074.type){case"system":return false;default:return true}}
function n075(A075){switch(A075.type){case"system":return false;default:return true}}
function n076(A076){switch(A076.type){case"system":return false;default:return true}}
function n077(A077){switch(A077.type){case"system":return false;default:return true}}
function n078(A078){switch(A078.type){case"system":return false;default:return true}}
function n079(A079){switch(A079.type){case"system":return false;default:return true}}
function n080(A080){switch(A080.type){case"system":return false;default:return true}}
function n081(A081){switch(A081.type){case"system":return false;default:return true}}
function n082(A082){switch(A082.type){case"system":return false;default:return true}}
function n083(A083){switch(A083.type){case"system":return false;default:return true}}
function n084(A084){switch(A084.type){case"system":return false;default:return true}}
function n085(A085){switch(A085.type){case"system":return false;default:return true}}
function n086(A086){switch(A086.type){case"system":return false;default:return true}}
function n087(A087){switch(A087.type){case"system":return false;default:return true}}
function n088(A088){switch(A088.type){case"system":return false;default:return true}}
function n089(A089){switch(A089.type){case"system":return false;default:return true}}
function n090(A090){switch(A090.type){case"system":return false;default:return true}}
function n091(A091){switch(A091.type){case"system":return false;default:return true}}
function n092(A092){switch(A092.type){case"system":return false;default:return true}}
function n093(A093){switch(A093.type){case"system":return false;default:return true}}
function n094(A094){switch(A094.type){case"system":return false;default:return true}}
function n095(A095){switch(A095.type){case"system":return false;default:return true}}
function n096(A096){switch(A096.type){case"system":return false;default:return true}}
function n097(A097){switch(A097.type){case"system":return false;default:return true}}
function n098(A098){switch(A098.type){case"system":return false;default:return true}}
function n099(A099){switch(A099.type){case"system":return false;default:return true}}
function n100(A100){switch(A100.type){case"system":return false;default:return true}}
function n101(A101){switch(A101.type){case"system":return false;default:return true}}
function n102(A102){switch(A102.type){case"system":return false;default:return true}}
function n103(A103){switch(A103.type){case"system":return false;default:return true}}
function n104(A104){switch(A104.type){case"system":return false;default:return true}}
function n105(A105){switch(A105.type){case"system":return false;default:return true}}
function n106(A106){switch(A106.type){case"system":return false;default:return true}}
function n107(A107){switch(A107.type){case"system":return false;default:return true}}
function n108(A108){switch(A108.type){case"system":return false;default:return true}}
function n109(A109){switch(A109.type){case"system":return false;default:return true}}
function n110(A110){switch(A110.type){case"system":return false;default:return true}}
function n111(A111){switch(A111.type){case"system":return false;default:return true}}
function n112(A112){switch(A112.type){case"system":return false;default:return true}}
function n113(A113){switch(A113.type){case"system":return false;default:return true}}
function n114(A114){switch(A114.type){case"system":return false;default:return true}}
function n115(A115){switch(A115.type){case"system":return false;default:return true}}
function n116(A116){switch(A116.type){case"system":return false;default:return true}}
function n117(A117){switch(A117.type){case"system":return false;default:return true}}
function n118(A118){switch(A118.type){case"system":return false;default:return true}}
function n119(A119){switch(A119.type){case"system":return false;default:return true}}
function n120(A120){switch(A120.type){case"system":return false;default:return true}}
function n121(A121){switch(A121.type){case"system":return false;default:return true}}
function n122(A122){switch(A122.type){case"system":return false;default:return true}}
function n123(A123){switch(A123.type){case"system":return false;default:return true}}
function n124(A124){switch(A124.type){case"system":return false;default:return true}}
function n125(A125){switch(A125.type){case"system":return false;default:return true}}
function n126(A126){switch(A126.type){case"system":return false;default:return true}}
function n127(A127){switch(A127.type){case"system":return false;default:return true}}
function n128(A128){switch(A128.type){case"system":return false;default:return true}}
function n129(A129){switch(A129.type){case"system":return false;default:return true}}
function n130(A130){switch(A130.type){case"system":return false;default:return true}}
function n131(A131){switch(A131.type){case"system":return false;default:return true}}
function n132(A132){switch(A132.type){case"system":return false;default:return true}}
